# Generated by Django 5.1.2 on 2024-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini1', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
