# Generated by Django 5.1.2 on 2024-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini1', '0003_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='address',
            new_name='specs',
        ),
    ]
