# Generated by Django 5.1.2 on 2024-11-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini1', '0004_rename_address_book_specs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='phone',
            new_name='rating',
        ),
    ]
