# Generated by Django 5.1.2 on 2024-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini1', '0005_rename_phone_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
